### ISSUE TITLE
Pre-trained models and inference example?

### ISSUE THREAD

**Issue by AkshayBhatAI** [google-research/pix2struct#1]
Hi are the pre-trained models released and is there an example for performing inference using the objective used for pre-training. 

Thanks!

**Comment by kentonl** [comment]
Yes, the pretrained models are released and specified in the `configs/init` config files. For example, the base model is specified at https://github.com/google-research/pix2struct/blob/main/pix2struct/configs/init/pix2struct_base_init.gin.

We just released code for doing standalone inference, and you can do that with the pretrained checkpoints. Please see https://github.com/google-research/pix2struct#inference for instructions.
