### ISSUE TITLE
Docs: macos `pip install -e .[dev]` -> `pip install -e ."[dev]"`

### ISSUE THREAD

**Issue by rayquaza7** [google-research/pix2struct#13]
More info here: https://github.com/mu-editor/mu/issues/852

`pip install -e .[dev] -f https://storage.googleapis.com/jax-releases/libtpu_releases.html` ->
`pip install -e ."[dev]" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html`

**Comment by kentonl** [comment]
Thanks for the suggestion. The documentation has been updated. Please do note that we don't support officially macOS.
