### ISSUE TITLE
How can I do the pre-training job on my local PC?

### ISSUE THREAD

**Issue by DLGreenhand** [google-research/pix2struct#48]
Do I have to do the pre-training job on Google Cloud Storage?
Looking forward to and thank you for your reply.

**Comment by gondimjoaom** [comment]
Hey, I am also trying to fine tune Pix2Struct locally. Did you manage to do so?

**Comment by nbroad1881** [comment]
You can use this as a starting point: https://github.com/huggingface/notebooks/blob/main/examples/image_captioning_pix2struct.ipynb
