### ISSUE TITLE
Release of fine-tuned weights

### ISSUE THREAD

**Issue by younesbelkada** [google-research/pix2struct#5]
Hi there!
Thanks for this model and codebase, we are keen to add this model on Hugging Face `transformers`, is there any reason why the fine-tuned weights are not public yet? Is there also a plan to release the fine-tuned checkpoints at some point? 
Thanks!

related: https://github.com/huggingface/transformers/issues/20663

**Comment by kentonl** [comment]
Done! Please see https://github.com/google-research/pix2struct/blob/main/README.md#finetuned-checkpoints.
