### ISSUE TITLE
RefExp build fails due to missing `processed_dir` flag

### ISSUE THREAD

**Issue by ivelin** [google-research/pix2struct#7]
[RefExp processing step](https://github.com/google-research/pix2struct#refexp) in README.md fails with `missing FLAG.processed_dir` error.

I was able to work around the error by providing a default value of 'processed` in the following source file.

https://github.com/google-research/pix2struct/blob/08eb4ca7cf5f5bfac2e49f92b719f7262d15d0ff/pix2struct/preprocessing/convert_refexp.py#L40

**Comment by kentonl** [comment]
Thanks! This has been fixed in [37413e3](https://github.com/google-research/pix2struct/commit/37413e317bb05c0350c73a59e86e03ccda917a2d).
