### ISSUE TITLE
export GCP_PROJECT=<your_project> should be your_project_ID

### ISSUE THREAD

**Issue by ivelin** [google-research/pix2struct#8]
GCP distinguishes between display project name and ID. They are not always the same. This caused a build error for me. It might save other folks time if the README corrects this line in the [Data Preprocessing](https://github.com/google-research/pix2struct#data-preprocessing) section to:

```
export GCP_PROJECT=<your_project_ID> 
```

**Comment by kentonl** [comment]
Thanks for noting this. This has been clarified in [37413e3](https://github.com/google-research/pix2struct/commit/37413e317bb05c0350c73a59e86e03ccda917a2d)
